swagger: '2.0'
info:
  title: RESEARCH_DATA_SUSHI API
  description: >-
    The RESEARCH_DATA_SUSHI API represents a RESTful implementation of SUSHI
    automation intended to returns COUNTER Research Data Release 1 reports and snippets of usage in JSON format
  termsOfService: ''
  contact:
    name: NISO SUSHI Standing Committee
    url: 'http://www.niso.org/workrooms/sushi'
    email: nisohq@niso.org
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: "1.0.0"
# host: sushi.sample.com
# basePath: /researchdata/rd1
schemes:
  - https
securityDefinitions:
  apikey:
    type: apiKey
    description: >-
      Unique code assigned by Content Provider to grant you access to this API. The apikey needs to be a query parameter for every operation to access this API.
    name: apikey
    in: query
  requestor_id:
    type: apiKey
    description: Identifies the requester(client) that is asking for report data
    name: requestor_id
    in: query
security:
  - apikey: []
    requestor_id: []
paths:
  /status:
    get:
      operationId: getAPIStatus
      description: >-
        This resource returns the current status of the reporting service supported by this API.
      produces:
        - application/json
      parameters:
        - name: platform
          in: query
          description: >-
            Name of the Platform the report data is being requested for.  This can be omitted if the service provides report data for only one platform.
          required: false
          type: string
      responses:
        '200':
          description: Status of the reporting service(s) supported by this API.
          schema:
            type: array
            items:
              $ref: '#/definitions/SUSHI_service_status'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/SUSHI_error_model'
  /reports:
    get:
      operationId: getReports
      description: >-
        This resource returns a list of reports supported by the API for a given application.
      produces:
        - application/json
      parameters:
        - name: platform
          in: query
          description: >-
            The name of the Platform the report data is being requested for.  This can be omitted if the service provides report data for only one platform.
          required: false
          type: string
        - name: search
          in: query
          description: >-
            Keyword search filtered against report name. Allows for searching for a report by name.
          required: false
          type: string
      responses:
        '200':
          description: List of reports supported by this service for this application.
          schema:
            type: array
            items:
              $ref: '#/definitions/SUSHI_report_list'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/SUSHI_error_model'
  /reports/dsr:
    get:
      operationId: getReportsDSR
      description: 'This resource returns the COUNTER Dataset Master Report [DSR].'
      produces:
        - application/json
      parameters:
        - name: platform
          in: query
          description: >-
            Name of the Platform the usage is being requested for.  This can be omitted if the service provides usage for only one platform.
          required: false
          type: string
        - name: begin_date
          in: query
          description: Usage start date in the form of yyyy-mm-dd or yyyy-mm.
          required: true
          type: string
        - name: end_date
          in: query
          description: Usage end date in the form of yyyy-mm-dd or yyyy-mm.
          required: true
          type: string
        - name: dataset_id
          in: query
          description: >-
            Optional Report Filter. Identifier of a specific dataset usage is being requested for.  If omitted, all datasets on the platform with usage for the requested customer will be returned
          required: false
          type: string
        - name: dataset_contributor
          in: query
          description: >-
            Optional Report Filter. Identifier of a specific contributor (e.g. author) usage is being requested for.  If omitted, all databases on the platform with usage for the requested customer will be returned
          required: false
          type: string
        - name: metric_type
          in: query
          description: >-
            Optional Report Filter. A list of Metric_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all metric_types with statistics.
          required: false
          type: string
        - name: data_type
          in: query
          description: >-
            Optional Report Filter. A list of Data_Types to return usage for.  Use | character to delimit multiple values. Omit this parameter to include all Data_Types with statistics. 
          required: false
          type: string
        - name: yop
          in: query
          description: >-
            Optional Report Filter. A list or range of years of publication to return in response in format of yyyy|yyyy|yyyy-yyyy. Note that 0001 = unknown
          required: false
          type: string
        - name: access_method
          in: query
          description: >-
            Optional Report Filter. A list of Access_Methods to return usage for --  delimited with a | character.
          required: false
          type: string
        - name: attributes_to_show
          in: query
          description: >-
            Optional Report Attribute. A list of attributes to include as separate elements in response (usage will be broken out by attribute values).  Multiple attribute names are delimited with a | character. Options include  Access_Method and YOP. When fields are  included usage will be presented for each value of that field (with usage) otherwise usage will be rolled up for all values of a given field.
          required: false
          type: string
        - name: exclude_report_header
          in: query
          description: Optional Report Attribute. Include this parameter with a value of 'true' to exclude the SUSHI Report_Header should be excluded with the response. Omitting the parameter will include the Report_Header.
          required: false
          type: boolean
        - name: exclude_monthly_details
          in: query
          description: >-
            Optional Report Attribute. Include this parameter with a value of 'true' to only show the Reporting Period Total for usage counts.
          required: false
          type: boolean
      responses:
        '200':
          description: 'Dataset Master Report (DSR).'
          schema:
            $ref: '#/definitions/COUNTER_dataset_report'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/SUSHI_error_model'
definitions:
  SUSHI_error_model:
    type: object
    description: Generalized format for presenting errors and exceptions.
    required:
      - Code
      - Severity
      - Message
    properties:
      Code:
        type: integer
        format: int32
        description: Error number. See table of error.
        example: 3040
      Severity:
        type: string
        description: Severity of the error.
        example: Warning
        enum:
          - Warning
          - Fatal
          - Debug
          - Info
      Message:
        type: string
        description: Text describing the error.
        example: Partial Data Returned.
      Help_URL:
        type: string
        description: URL describing error details.
      Data:
        type: string
        description: Additional data provided by the server to clarify the error.
        example: Usage data has not been processed for all requested months.
  SUSHI_report_header:
    type: object
    description: >-
      Generalized report header that defines the requested report, the
      requestor, the customer, filters applied, reportAttributes applied and any
      exceptions.
    required:
      - Report_Name
      - Report_ID
      - Release
    properties:
      Report_Name:
        type: string
        description: The long name of the report.
        example: Dataset Report
      Report_ID:
        type: string
        description: >-
          The report ID or code or shortname. Typically this will be the same code provided in the Report parameter of the request.
        example: DSR
      Release:
        type: string
        description: The release or version of the report.
        example: 'RD1'
      Created:
        type: string
        format: dateTime
        description: Time the report was prepared. Format as defined by date-time - RFC3339
        example: '2016-09-08T22:47:31Z'
      Created_By:
        type: string
        description: Name of the organization producing the report.
        example: 'DataONE'
      Report_Filters:
        type: array
        description: >-
          Zero or more report filters used for this report.  Typically  reflect filters provided on the Request.  Filters limit the data to be reported on.
        items:
          required:
            - Name
            - Value
          properties:
            Name:
              type: string
              description: Name of the report filter.
              example: Begin_Date
            Value:
              type: string
              description: Value of the report filter.
              example: 2015-01
      Report_Attributes:
        type: array
        description: >-
          Zero or more additional attributes applied to the report. Attributes inform the level of detail in the report.
        items:
          required:
            - Name
            - Value
          properties:
            Name:
              type: string
              description: Name of the report attribute.
              example: Exclude_Monthly_Details
            Value:
              type: string
              description: Name of the report attribute.
              example: 'True'
      Exceptions:
        type: array
        description: Series of exceptions encounted when preparing the report.
        items:
          $ref: '#/definitions/SUSHI_error_model'
  SUSHI_report_list:
    type: object
    required:
      - Report_ID
      - Report_Name
      - Release
      - Report_Description
    properties:
      Report_Name:
        type: string
        description: The long name of the report
        example: Dataset Report
      Report_ID:
        type: string
        description: >-
          The code, ID or short name of the report that is be used in the request to identify the report.
        example: DSR
      Release:
        type: string
        description: The release or version number of the report.
        example: 'RD1'
      Report_Description:
        type: string
        description: A short sentence describing the report.
        example: Usage by Month and Dataset
      Path:
        type: string
        description: The path to use when requesting this report on this service.
        example: /reports/dsr
  SUSHI_service_status:
    type: object
    required:
      - ServiceActive
    properties:
      Description:
        type: string
        description: Description of the service.
        example: COUNTER Research Data Usage Reports for the UK Data Service - ReShare.
      ServiceActive:
        type: boolean
        description: Indicator if the service is currently able to deliver reports.
        example: true
      RegistryURL:
        type: string
        description: >-
          If available, the URL separate registry with additional information about the service.
        example: 'https://www.projectcounter.org/counter-user/ebsco-database/'
      Note:
        type: string
        description: A general note about the service.
        example: >-
          A given customer can request a maximum of 5 requests per day for a given report
      Alerts:
        type: array
        description: Any alerts related to service interuptions and status.
        items:
          type: object
          properties:
            Date_Time:
              type: string
              format: dateTime
              description: Date-time of the alert.
              example: '2016-08-02: 12:54'
            Alert:
              type: string
              description: Text of the alert.
              example: Service will be unavailable Sunday midnight...
  COUNTER_dataset_report:
    type: object
    description: Describes the formatting needs for the COUNTER Dataset Report. Response may include the Report_Header (optional), Report_Datasets (usage stats).
    required:
      - Report_Datasets
    properties:
      Report_Header:
        $ref: '#/definitions/SUSHI_report_header'
      Report_Datasets:
        type: array
        items:
          $ref: '#/definitions/COUNTER_dataset_usage'
  COUNTER_dataset_usage:
    type: object
    description: Defines the output for the Report_Datasets being returned in a Dataset Report.
    required:
      - Dataset_Title
      - Publisher
      - Publisher_ID
      - Platform
      - Data_Type
      - Performance
    properties:
      Dataset_Title:
        type: string
        description: Name of the dataset being reported.
        example: Lake Erie Fish Community Data
      Dataset_ID:
        type: array
        items:
          $ref: '#/definitions/COUNTER_dataset_identifiers'
        description: The identifier for the report dataset
      Dataset_Contributors:
        type: array
        items:
          $ref: '#/definitions/COUNTER_dataset_contributors'
        description: The identifier for contributor (i.e. creator) of the dataset.
      Dataset_Dates:
        type: array
        items:
          $ref: '#/definitions/COUNTER_dataset_dates'
        description: >-
          Publication or other date(s)related to the dataset.
      Dataset_Attributes:
        type: array
        items:
          $ref: '#/definitions/COUNTER_dataset_attributes'
        description: Other attributes related related to the dataset.
      Platform:
        type: string
        description: Name of the platform
        example: DataONE
      Publisher:
        type: string
        description: Name of publisher of the dataset
        example: DataONE
      Publisher_ID:
        type: array
        items:
          $ref: '#/definitions/COUNTER_publisher_identifiers'
        description: The identifier for the publisher.
      Data_Type:
        type: string
        description: Nature of the dataset being reported.
        enum:
          - Dataset
        example: Dataset
      YOP:
        type: string
        description: >-
          Year of publication in the format of 'yyyy'. Use '0001' for unknown and '9999' for articles in press.
        example: '2010'
      Access_Method:
        type: string
        description: >-
          Identifies if the usage activity was 'Regular' usage - a user doing research on a content site, or if the usage activity was 'Machine' - for the purpose of retrieving content for Text and Data Mining (TDM)
        enum:
          - Regular
          - Machine
        example: Regular
      Performance:
        type: array
        items:
          $ref: '#/definitions/COUNTER_dataset_performance'
        description: The usage data related to the report dataset
  COUNTER_dataset_identifiers:
    type: object
    required:
      - Type
      - Value
    properties:
      Type:
        type: string
        example: DOI
        enum:
          - DOI
          - Proprietary
          - URI
      Value:
        type: string
        description: Value of the dataset identifier
        example: 0931-865
  COUNTER_publisher_identifiers:
    type: object
    required:
      - Type
      - Value
    properties:
      Type:
        type: string
        example: ORCID
        enum:
          - ISNI
          - ORCID
      Value:
        type: string
        description: Value of the publisher identifier
        example: 1234-1234-1234-1234
  COUNTER_dataset_contributors:
    type: object
    required:
      - Type
      - Value
    properties:
      Type:
        type: string
        example: Name
        enum:
          - Name
          - ORCID
          - ISNI
      Value:
        type: string
        description: Value of the contributor identifier
        example: John Smith
  COUNTER_dataset_dates:
    type: object
    required:
      - Type
      - Value
    properties:
      Type:
        type: string
        example: Pub_Date
        enum:
          - Pub_Date
          - First_Accessed_Online
          - Proprietary
      Value:
        type: string
        description: Value of the dataset date
        example: '2002-01-15'
  COUNTER_dataset_attributes:
    type: object
    required:
      - Type
      - Value
    properties:
      Type:
        type: string
        description: >-
          Item attribute types are defined by NISO Journal Article Version and other work...
        example: Dataset_Version
        enum:
          - Dataset_Version
          - Dataset_Type
          - Proprietary
      Value:
        type: string
        description: Value of the item attribute
        example: VoR
  COUNTER_dataset_performance:
    type: object
    required:
      - Period
      - Instance
    properties:
      Period:
        type: object
        required:
          - Begin_Date
          - End_Date
        properties:
          Begin_Date:
            type: string
            description: Beginning date for usage in this 'datasetPerformance' instance.
            example: '2015-01-01'
          End_Date:
            type: string
            description: Ending date for usage in this 'datasetPerformance' instance.
            example: '2015-01-31'
      Instance:
        type: array
        items:
          type: object
          required:
            - Metric_Type
            - Count
          properties:
            Metric_Type:
              type: string
              description: Type of activity being counted.
              example: Total_Dataset_Requests
              enum:
                - Total_Dataset_Investigations
                - Total_Dataset_Requests
                - Unique_Dataset_Investigations
                - Unique_Dataset_Requests
            Count:
              type: integer
              description: >-
                Usage count > 0.  If count is zero, the Intance element should be excluded.
              example: 21
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /COUNTER/researchdata-sushi_1_0_api/1.0.0